### ISSUE TITLE
Inferred latent vector

### ISSUE THREAD

**Issue by vinayakrajurs** [cchallu/spectranet#2]
Good Day,
Thank you for sharing the code implementation.
In the paper you have mentioned that z* is the inferred latent vector and L is a reconstruction error metric, 
However I'm fairly new to to this topic and wasn't able to match this equation with the code, It would be really helpful if i can get some 
insights on it
![image](https://user-images.githubusercontent.com/88593317/205304484-1a7df536-3c9b-4a29-a465-4a2b7ad04165.png)

thank you

**Comment by cchallu** [comment]
Hi @vinayakrajurs! Thanks for your interest in our model. The inference of latent vectors is performed in the `infer_z` method.

<img width="856" alt="image" src="https://user-images.githubusercontent.com/31133398/205364906-322f015d-bd8b-471c-8713-bf9c33327e39.png">

**Comment by vinayakrajurs** [comment]
Thank you so much
